{% set name = "pantools" %}
{% set version = "3.3.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://git.wur.nl/bioinformatics/pantools.git
  git_rev: {{ version }}
  git_depth: -1

build:
  noarch: generic
  number: 0

requirements:
  build:
    - openjdk =8
    - maven
    - git
    - {{ compiler('cxx') }}
  run:
    - python
    - openjdk =8
    - mcl
    - kmc

test:
  commands:
    - pantools version

about:
  home: https://git.wur.nl/bioinformatics/pantools
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: "PanTools is a pangenomic toolkit for comparative analysis of large number of genomes."
  description: |
    PanTools is a pangenomic toolkit for comparative analysis of large number
    of genomes. It is developed in the Bioinformatics Group of Wageningen
    University, the Netherlands. Please cite the relevant publication(s) from
    the list of publications if you use PanTools in your research.


extra:
  notes: |
    PanTools is Java program that comes with a custom wrapper Python script.
    This wrapper is called "pantools" and is on $PATH by default. By default
    "-Xms512m -Xmx1g" is set in the wrapper. If you want to overwrite it you can
    specify these values directly after your binaries. If you have _JAVA_OPTIONS
    set globally this will take precedence.
    For example run it with "pantools -Xms512m -Xmx1g"
  identifiers:
    - doi:https://doi.org/10.1093/bioinformatics/btw455
    - doi:https://doi.org/10.1186/s12859-018-2362-4
    - doi:https://doi.org/10.1101/813634
